const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),src=path.join(root,'frontend'),dist=path.join(root,'dist');
fs.mkdirSync(dist,{recursive:true});
for(const name of ['index.html','styles.css','config.js','core.js','sample.js','app.js'])fs.copyFileSync(path.join(src,name),path.join(dist,name));
fs.writeFileSync(path.join(dist,'.nojekyll'),'');
let html=fs.readFileSync(path.join(src,'index.html'),'utf8');
const safeScript=s=>s.replace(/<\/script/gi,'<\\/script');
html=html.replace('<link rel="stylesheet" href="styles.css">',()=>'<style>'+fs.readFileSync(path.join(src,'styles.css'),'utf8')+'</style>');
for(const file of ['config.js','core.js','sample.js','app.js'])html=html.replace(`<script src="${file}"></script>`,()=>`<script>${safeScript(fs.readFileSync(path.join(src,file),'utf8'))}</script>`);
fs.writeFileSync(path.join(root,'apps-script','Index.html'),html);
fs.copyFileSync(path.join(src,'core.js'),path.join(root,'apps-script','Core.gs'));
console.log('Built GitHub Pages dist/ and Apps Script Index.html + Core.gs. No dependencies required.');
